//
// Created by cacoethes on 9/21/20.
//

#ifndef PERFORMANCEEXPERIMENT_GLOBALMACRO_H
#define PERFORMANCEEXPERIMENT_GLOBALMACRO_H
#define TRIAL_COUNT 10000

#endif //PERFORMANCEEXPERIMENT_GLOBALMACRO_H
